### ISSUE TITLE
Get duplicate tweets

### ISSUE THREAD

**Issue by shizia** [twintproject/twint#961]
### Initial Check
>Make sure you've checked the following:

- [] Python version is 3.8;
- [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
c = twint.Config()
c.Search = "keyword"
c.Limit = 100
c.Location=True
c.Since="2019-07-01"
c.Until="2019-07-02"
twint.run.Search(c)
tlist = c.search_tweet_list

### Description of Issue
>Of the 100 tweets I got, only about 20 are unique. How to solve this problem and get more unique tweets? 

### Environment Details
>Using Windows, py3.8

**Comment by himanshudabas** [comment]
did you get the following error while running the above script?
`AttributeError: 'Config' object has no attribute 'search_tweet_list'`

If not then I doubt that you are using the current master branch of the library.
Please try to uninstall and reinstall _twint_ and then try to run the script again.

**Comment by shizia** [comment]
> did you get the following error while running the above script?
> `AttributeError: 'Config' object has no attribute 'search_tweet_list'`
> 
> If not then I doubt that you are using the current master branch of the library.
> Please try to uninstall and reinstall _twint_ and then try to run the script again.

I didn't get the error. And I uninstall and reinstall twint, but there are still lots of duplicate tweets.

**Comment by himanshudabas** [comment]
I am unable to replicate your issue. can you specify the following details :
1. Are you using the `system wide` installation of Python / `Virtual Env` / `Anaconda Env` ?
2. what command did you use to install _twint_ ?
3. Whats the exact script you ran? is the above script the one you ran or did you make any changes in it?

**Comment by shizia** [comment]
1. I'm sorry that I don't know if my python is system wide. How to check?
2. After uninstalling twint just now, I used "pip install twint" to install, and got a lot of duplicate tweets. Then I uninstalled it again, used "pip3 install twint" , now it have the error "CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)". I have ever met this error before, and at that time I found a solution in issue #917 ,using  `pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2`.But it seems that using that way the tweets are duplicate?
3.After that ,I run
`for i in tlist:
    print("NO.",index," ",i)
    c.Username=i['username']
    c.Output="keyword.csv"
    twint.run.Lookup(c)`

I am new in this , if my response is inappropriate I will apologize for it.
Thank you for your patience！

**Comment by himanshudabas** [comment]
_I apologize if I somehow came out to be rude, I did not mean to be rude._

Please refer to #941, check my comments in that _issue_. This problem has already been solved.
You simply need to install using `pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint` and then run the script the way you were running before. It will solve your issue.

**Comment by shizia** [comment]
Thanks! I did it, but then `AttributeError: 'Config' object has no attribute 'search_tweet_list'`  occurred, as you said above.  Now I'm trying the way on pull #917 `pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2` .

**Comment by himanshudabas** [comment]
That's because that method doesn't exist in the library that you installed.
It was proposed in #917 but it was not merged into the _twint_ master branch because it had some issues.
In the library that you have installed now, you get the tweet results in a csv file instead of a variable like `search_tweet_list`

For saving the search result to a csv file you need to add the following line to your script :
```
c.Store_csv = True
c.Output = 'tweet_results.csv'
```

After the search is complete you'd find your CSV file at the location where you are running your script from.

**Comment by shizia** [comment]
Oh, I did it but `No more data. finished scraping!! is it though? because sometimes twitter lie.` occurred. Is it because  twitter's new endpoints aren't working with aiohttp on Python 3.8.6 ?

**Comment by himanshudabas** [comment]
did you get any results?
and what script did you ran exactly?

**Comment by shizia** [comment]
I didn't get any results, only this sentence. I run
`c = twint.Config()
c.Search = "keyword"
c.Limit = 50
c.Location=True
c.Since="2019-07-01"
c.Until="2019-07-02"
c.Store_csv = True
c.Output = 'tweet_results.csv'
twint.run.Search(c)
`
and also didn't get the file.

**Comment by shizia** [comment]
It is too bad. Is this related to the version of python?

**Comment by himanshudabas** [comment]
> It is too bad. Is this related to the version of python?

no it's not related to python version.
just make the range of `since` and `until` greater than 1 day. It is related to a separate issue, unrelated to python version.

change `c.Until` value to `2019-07-04` and see if this works

**Comment by shizia** [comment]
The same.

**Comment by himanshudabas** [comment]
Okay I figured it out. It is happening due the bug I mentioned above, but I didn't realize this bug was so severe until just now.
I could quickly fix this issue but this won't be solved in _twint_ until my branch is merged into _twint_.

So you'll have to wait until I put up a fix for this.

**Comment by shizia** [comment]
I see. I will wait, thank you very much !!!

**Comment by himanshudabas** [comment]
A temporary fix for you would be to increase the `c.Limit` from 100 to a much larger number. perhaps **1000**.
I'm sure this would work for you. but remember this is a temporary fix, and still you won't be getting all the tweets. Also this won't work for every query.

**Comment by shizia** [comment]
Well, it didn't work for me still ,I only got your sentence. Maybe waiting for your fix will be a better choice ,hahaha.

**Comment by HegdeChaitra** [comment]
> ### Initial Check
> > Make sure you've checked the following:
> 
> * [] Python version is 3.8;
> * [] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
> * [] I have searched the issues and there are no duplicates of this issue/question/request.
> 
> ### Command Ran
> c = twint.Config()
> c.Search = "keyword"
> c.Limit = 100
> c.Location=True
> c.Since="2019-07-01"
> c.Until="2019-07-02"
> twint.run.Search(c)
> tlist = c.search_tweet_list
> 
> ### Description of Issue
> > Of the 100 tweets I got, only about 20 are unique. How to solve this problem and get more unique tweets?
> 
> ### Environment Details
> > Using Windows, py3.8

@shizia This is a temporary fix : #941 
Twint needs to be installed as shown in #917 using `pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2` . I've been using it intensively for last 2 weeks and it's doing its job.

**Comment by HegdeChaitra** [comment]
> Well, it didn't work for me still ,I only got your sentence. Maybe waiting for your fix will be a better choice ,hahaha.

@shizia Use the temporary fix in the following issue : #941 

Twint needs to be installed as shown in #917 using `pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2` . I've been using it intensively for last 2 weeks and it's doing its job - seem to be fetching all the tweets.

**Comment by shizia** [comment]
> > Well, it didn't work for me still ,I only got your sentence. Maybe waiting for your fix will be a better choice ,hahaha.
> 
> @shizia Use the temporary fix in the following issue : #941
> 
> Twint needs to be installed as shown in #917 using `pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2` . I've been using it intensively for last 2 weeks and it's doing its job - seem to be fetching all the tweets.

I uninstall twint and install it again by using that command, but I got no tweet

**Comment by HegdeChaitra** [comment]
> > > Well, it didn't work for me still ,I only got your sentence. Maybe waiting for your fix will be a better choice ,hahaha.
> > 
> > 
> > @shizia Use the temporary fix in the following issue : #941
> > Twint needs to be installed as shown in #917 using `pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2` . I've been using it intensively for last 2 weeks and it's doing its job - seem to be fetching all the tweets.
> 
> I uninstall twint and install it again by using that command, but I got no tweet

It might be something to do with `config.search`. For nbc related tweets, I set  `c.Search = "from:@nbcnews" `. Can you try running this comment[https://github.com/twintproject/twint/issues/941#issuecomment-704916950] from #941  as is and let me know ?

**Comment by HegdeChaitra** [comment]
> > > Well, it didn't work for me still ,I only got your sentence. Maybe waiting for your fix will be a better choice ,hahaha.
> > 
> > 
> > @shizia Use the temporary fix in the following issue : #941
> > Twint needs to be installed as shown in #917 using `pip3 install --user --upgrade git+https://github.com/yunusemrecatalcam/twint.git@twitter_legacy2` . I've been using it intensively for last 2 weeks and it's doing its job - seem to be fetching all the tweets.
> 
> I uninstall twint and install it again by using that command, but I got no tweet

I have also pushed the code and output into [my github](https://github.com/HegdeChaitra/twitter_news_data). The code for scraping can be found [here](https://github.com/HegdeChaitra/twitter_news_data/blob/master/get_tweets.py) and output can be found [here](https://github.com/HegdeChaitra/twitter_news_data/blob/master/get_tweets.py)
