### ISSUE TITLE
twint not working ~ py3.7, ImportError: cannot import name 'datelock'

### ISSUE THREAD

**Issue by 0x746866** [twintproject/twint#332]
OS: Manjaro 4.18
Kernel: Linux 4.18-MANJARO
DE: i3wm
Python: v3.7

I am unable to run twint, regardless of the method used to install. All attempts to install, be it through pip, venv, or git cloning, when running the script produce the following error:

```
 thief@nexion  ~  cd /usr/lib/python3.7/site-packages/twint
 thief@nexion  /usr/lib/python3.7/site-packages/twint  ls
config.py    format.py    output.py    storage   user.py
datelock.py  get.py       __pycache__  tweet.py  verbose.py
feed.py      __init__.py  run.py       url.py    __version__.py
 thief@nexion  /usr/lib/python3.7/site-packages/twint  python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from . import datelock, feed, get, output, verbose, storage
ImportError: cannot import name 'datelock' from '__main__' (run.py)
```

**Comment by pielco11** [comment]
I guess that's a compatibility error, I have it running in different platforms. I'm going to look at it soon

Thank you for reporting!

**Comment by pielco11** [comment]
@0x746866 Twint works with `python3.7` be sure to run the correct script
